### PR TITLE
chore: add storybook test-runner

### PR DESCRIPTION
**Pull request by filiptammergard**
- feat(BaseInput): set aria-describedby
- chore: add storybook test-runner

### CODE REVIEW

**Comment by filiptammergard** [comment]
@SocketSecurity ignore playwright@1.27.1
@SocketSecurity ignore playwright-core@1.27.1
@SocketSecurity ignore jest@28.1.3
@SocketSecurity ignore jest-cli@28.1.3

**Comment by filiptammergard** [comment]
@SocketSecurity ignore playwright@1.27.1

**Comment by filiptammergard** [comment]
@SocketSecurity ignore jest-cli@28.1.3 jest@28.1.3 playwright-core@1.27.1

**Comment by filiptammergard** [comment]
@SocketSecurity ignore jest@28.1.3

**Review by jenseo — APPROVED** [review]
Wow, this looks cool!

**Pull request merged**
